### PR TITLE
Add support for Celestica Belgite; bugs fixed

### PR DESCRIPTION
**Pull request by nicwu-cel**
Add basic support for Celestica Belgite
Complement forceoff/forcerestart function for Celestica Belgite 
Add patch to support more than one thermal sensor per PSU 
Add dynamic-link library nghttp2 to support HTTP service

- CPU: Intel Denverton
- MAC: Broadcom BCM56277
- Network: 48x10/100/1000M RJ45 ports and 8xSFP+

Signed-off-by: Nicholas Wu <nicwu@celestica.com>
Signed-off-by: Pradchaya Phucharoen <pphuchar@celestica.com>
Signed-off-by: Srikanth Krishnamachary <srikanth@celestica.com>
Signed-off-by: Ramar N <nramar@celestica.com>

### CODE REVIEW

**Comment by jcleung5549** [comment]
Can you review this PR at the next OpenRMC-DM meeting. Then the it can be labeled "Approved to Merge"?

**Comment by nicwu-cel** [comment]
May I know when the next OpenRMC-DM meeting will be hold and how to attend this meeting?

**Comment by jcleung5549** [comment]
The next OpenRMC-DM meeting with be Jan 10, 2023 (8am PT) - https://www.opencompute.org/projects/openrmc-dm

**Comment by nicwu-cel** [comment]
Thanks @jcleung5549 , 4 members of us would like to attend this meeting, they're

Jersey Yang, jersyang@celestica.com
Nicholas Wu, nicwu@celestica.com
Jeffrey Catlin, jcatlin@celestica.com 
Srikanth Krishnamachary, srikanth@celestica.com

I would really appreciate it if you could add us to the agenda.

**Comment by MaciejMis** [comment]
This PR was approved at OPENRMC-DM meeting.

**Comment by nicwu-cel** [comment]
This PR has been verified on 2023/1/11 in Celestica Belgite platform as below:

1. Add dynamic-link library nghttp2 to support HTTP service

```
root@localhost:~# dpkg -i psme-allinone.deb
(Reading database ... 18608 files and directories currently installed.)
Preparing to unpack psme-allinone.deb ...
psme-rest-server: no process found
psme-chassis: no process found
Unpacking psme-allinone (2.1.3.60.02) over (2.1.3.60.02) ...
psme-rest-server: no process found
psme-chassis: no process found
psme-rest-server is not running
psme-chassis is not running
Setting up psme-allinone (2.1.3.60.02) ...
root@localhost:~# service psme start
start_daemon!!
start_daemon!!
root@localhost:~# service psme status
psme-rest-server is running
root@localhost:~#
```

2. Add patch to support more than one thermal sensor per PSU

```
root@diag-ThinkStation-P330:~/nicholas/bcrypt-4.0.0# curl --insecure --user admin:redfish -v https://10.194.78.254:8888/redfish/v1/Chassis/1/Thermal | json_pp
*   Trying 10.194.78.254...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 10.194.78.254 (10.194.78.254) port 8888 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Unknown (8):
{ [6 bytes data]
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [1441 bytes data]
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [520 bytes data]
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=TW; ST=TAICHUNG; L=TAICHUNG; O=selfsignedCA; OU=Personal; CN=192.168.1.99
*  start date: Aug 30 23:41:26 2022 GMT
*  expire date: Aug 27 23:41:26 2032 GMT
*  issuer: C=TW; ST=TAICHUNG; L=TAICHUNG; O=selfsignedCA; OU=Personal; CN=192.168.1.99
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Server auth using Basic with user 'admin'
} [5 bytes data]
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
} [1 bytes data]
> GET /redfish/v1/Chassis/1/Thermal HTTP/1.1
> Host: 10.194.78.254:8888
> Authorization: Basic YWRtaW46cmVkZmlzaA==
> User-Agent: curl/7.58.0
> Accept: */*
>
{ [5 bytes data]
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
{ [1 bytes data]
< HTTP/1.1 200 OK
< Connection: Keep-Alive
< Content-Length: 5688
< Content-Type: application/json
< Date: Thu, 08 Sep 2022 06:05:47 GMT
<
{ [5 bytes data]
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
{ [1 bytes data]
100  5688  100  5688    0     0   120k      0 --:--:-- --:--:-- --:--:--  120k
* Connection #0 to host 10.194.78.254 left intact
{
   "Fans" : [
      {
         "ReadingUnits" : "RPM",
         "LowerThresholdNonCritical" : null,
         "Status" : {
            "HealthRollup" : "OK",
            "State" : "Enabled"
         },
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "UpperThresholdFatal" : null,
         "Name" : "System Fan 1",
         "Reading" : 13050,
         "PhysicalContext" : "Back",
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
         "UpperThresholdNonCritical" : null,
         "UpperThresholdCritical" : null,
         "MemberId" : "1"
      },
      {
         "UpperThresholdNonCritical" : null,
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
         "PhysicalContext" : "Back",
         "MemberId" : "2",
         "UpperThresholdCritical" : null,
         "Status" : {
            "State" : "Enabled",
            "HealthRollup" : "OK"
         },
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "LowerThresholdNonCritical" : null,
         "ReadingUnits" : "RPM",
         "Reading" : 11850,
         "UpperThresholdFatal" : null,
         "Name" : "System Fan 2"
      },
      {
         "UpperThresholdCritical" : null,
         "MemberId" : "3",
         "UpperThresholdNonCritical" : null,
         "PhysicalContext" : "Back",
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
         "Reading" : 11850,
         "Name" : "System Fan 3",
         "UpperThresholdFatal" : null,
         "LowerThresholdNonCritical" : null,
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "Status" : {
            "State" : "Enabled",
            "HealthRollup" : "OK"
         },
         "ReadingUnits" : "RPM"
      },
      {
         "PhysicalContext" : "PowerSupply",
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
         "UpperThresholdNonCritical" : null,
         "MemberId" : "4",
         "UpperThresholdCritical" : null,
         "ReadingUnits" : "RPM",
         "LowerThresholdNonCritical" : null,
         "Status" : {
            "State" : "Enabled",
            "HealthRollup" : "OK"
         },
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "Name" : "PSU 1 Fan 1",
         "UpperThresholdFatal" : null,
         "Reading" : 4352
      },
      {
         "MemberId" : "5",
         "UpperThresholdCritical" : null,
         "UpperThresholdNonCritical" : null,
         "PhysicalContext" : "PowerSupply",
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
         "Reading" : 4864,
         "UpperThresholdFatal" : null,
         "Name" : "PSU 2 Fan 1",
         "LowerThresholdNonCritical" : null,
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "Status" : {
            "HealthRollup" : "OK",
            "State" : "Enabled"
         },
         "ReadingUnits" : "RPM"
      }
   ],
   "Id" : "Thermal",
   "@odata.context" : "/redfish/v1/$metadata#Thermal.Thermal",
   "Description" : "Collection of Thermal Sensors",
   "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
   "Temperatures" : [
      {
         "Name" : "Chassis Thermal Sensor 1 Temperature",
         "UpperThresholdFatal" : 0,
         "LowerThresholdNonCritical" : 0,
         "Status" : {
            "HealthRollup" : "Critical",
            "State" : "Enabled"
         },
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "MemberId" : "1",
         "UpperThresholdCritical" : 0,
         "SensorNumber" : 1,
         "UpperThresholdNonCritical" : 55,
         "PhysicalContext" : "SystemBoard",
         "ReadingCelsius" : 32.75,
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal"
      },
      {
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "Status" : {
            "State" : "Enabled",
            "HealthRollup" : "Critical"
         },
         "LowerThresholdNonCritical" : 0,
         "Name" : "Chassis Thermal Sensor 2 Temperature",
         "UpperThresholdFatal" : 0,
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
         "PhysicalContext" : "SystemBoard",
         "ReadingCelsius" : 30.75,
         "UpperThresholdNonCritical" : 55,
         "SensorNumber" : 2,
         "MemberId" : "2",
         "UpperThresholdCritical" : 0
      },
      {
         "LowerThresholdNonCritical" : 0,
         "Status" : {
            "HealthRollup" : "OK",
            "State" : "Enabled"
         },
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "Name" : "Chassis Thermal Sensor 3 Temperature",
         "UpperThresholdFatal" : 78,
         "PhysicalContext" : "SystemBoard",
         "ReadingCelsius" : 36.5,
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
         "UpperThresholdNonCritical" : 72,
         "SensorNumber" : 3,
         "UpperThresholdCritical" : 75,
         "MemberId" : "3"
      },
      {
         "UpperThresholdFatal" : 0,
         "Name" : "Chassis Thermal Sensor 4 Temperature",
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "Status" : {
            "State" : "Enabled",
            "HealthRollup" : "Critical"
         },
         "LowerThresholdNonCritical" : 0,
         "SensorNumber" : 4,
         "MemberId" : "4",
         "UpperThresholdCritical" : 0,
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
         "ReadingCelsius" : 30.625,
         "PhysicalContext" : "SystemBoard",
         "UpperThresholdNonCritical" : 55
      },
      {
         "Name" : "System CPU Thermal Sensor 1 Temperature",
         "UpperThresholdFatal" : 105,
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "Status" : {
            "HealthRollup" : "OK",
            "State" : "Enabled"
         },
         "LowerThresholdNonCritical" : 0,
         "SensorNumber" : 5,
         "MemberId" : "5",
         "UpperThresholdCritical" : 93,
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
         "PhysicalContext" : "CPU",
         "ReadingCelsius" : 33,
         "UpperThresholdNonCritical" : 88
      },
      {
         "Name" : "PSU 1 Thermal Sensor 1 Temperature",
         "UpperThresholdFatal" : 0,
         "LowerThresholdNonCritical" : 0,
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "Status" : {
            "HealthRollup" : "Critical",
            "State" : "Enabled"
         },
         "SensorNumber" : 6,
         "MemberId" : "6",
         "UpperThresholdCritical" : 0,
         "PhysicalContext" : "PowerSupply",
         "ReadingCelsius" : 32,
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
         "UpperThresholdNonCritical" : 0
      },
      {
         "Status" : {
            "State" : "Enabled",
            "HealthRollup" : "Critical"
         },
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "LowerThresholdNonCritical" : 0,
         "Name" : "PSU 1 Thermal Sensor 2 Temperature",
         "UpperThresholdFatal" : 0,
         "UpperThresholdNonCritical" : 0,
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
         "PhysicalContext" : "PowerSupply",
         "ReadingCelsius" : 29,
         "UpperThresholdCritical" : 0,
         "MemberId" : "7",
         "SensorNumber" : 7
      },
      {
         "Status" : {
            "State" : "Enabled",
            "HealthRollup" : "Critical"
         },
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "LowerThresholdNonCritical" : 0,
         "UpperThresholdFatal" : 0,
         "Name" : "PSU 2 Thermal Sensor 1 Temperature",
         "UpperThresholdNonCritical" : 0,
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
         "PhysicalContext" : "PowerSupply",
         "ReadingCelsius" : 33,
         "UpperThresholdCritical" : 0,
         "MemberId" : "8",
         "SensorNumber" : 8
      },
      {
         "SensorNumber" : 9,
         "MemberId" : "9",
         "UpperThresholdCritical" : 0,
         "@odata.id" : "/redfish/v1/Chassis/1/Thermal",
         "ReadingCelsius" : 33,
         "PhysicalContext" : "PowerSupply",
         "UpperThresholdNonCritical" : 0,
         "UpperThresholdFatal" : 0,
         "Name" : "PSU 2 Thermal Sensor 2 Temperature",
         "Status" : {
            "HealthRollup" : "Critical",
            "State" : "Enabled"
         },
         "RelatedItem" : [
            {
               "@odata.id" : "/redfish/v1/Chassis/1"
            }
         ],
         "LowerThresholdNonCritical" : 0
      }
   ],
   "Redundancy" : [],
   "Name" : "Thermal",
   "@odata.type" : "#Thermal.v1_1_0.Thermal"
}
root@diag-ThinkStation-P330:~/nicholas/bcrypt-4.0.0#

```
3. Complement forceoff/forcerestart function for Celestica Belgite

ForceOff
```
diag@SSLLABN050-1:~$ curl --insecure --user admin:redfish  -X POST https://10.194.78.99:8888/redfish/v1/Chassis/1/Actions/Chassis.Reset -d '{"ResetType":"ForceOff"}'

Note：this command gets no feedback in Belgite platform and will return till timeout because unit has been forced off.

Unit Log:

root@localhost:~#
```

ForceRestart
```
diag@SSLLABN050-1:~$ curl --insecure --user admin:redfish  -X POST https://10.194.78.99:8888/redfish/v1/Chassis/1/Actions/Chassis.Reset -d '{"ResetType":"ForceRestart"}'
diag@SSLLABN050-1:~$

Unit Log:
root@localhost:~#



Primary BIOS boot in progress...

CPLD_C version: 0.6
CPLD_B version: 1.6
```

**Pull request merged**
